use colored::*;
use std::path::{Path, PathBuf};
use std::process::Command;

use regent::tester::bundled_gems::ensure_bundled_gems;

pub struct BootstrapCommand;

/// Gems Regent needs in order to run `regent test` against a Puppet module.
const REQUIRED_GEMS: &[(&str, &str)] = &[
    ("rspec", "~> 3.0"),
    ("rspec-puppet", "~> 3.0"),
    ("puppetlabs_spec_helper", ">= 5.0"),
];

impl BootstrapCommand {
    pub fn execute(path: &Path, force: bool) -> anyhow::Result<()> {
        let module_path = path
            .canonicalize()
            .unwrap_or_else(|_| path.to_path_buf());

        println!(
            "{} Bootstrapping Regent dependencies in {}",
            "⚙".cyan(),
            module_path.display()
        );

        ensure_gemfile(&module_path, force)?;

        match ensure_bundled_gems(&module_path) {
            Ok(Some(src)) => println!(
                "{} Copied Regent-shipped gems from {}",
                "✓".green().bold(),
                src.display()
            ),
            Ok(None) => println!(
                "{} No Regent-shipped gem cache found (will install via bundler)",
                "•".yellow()
            ),
            Err(err) => eprintln!(
                "{} Could not copy shipped gems: {err}",
                "!".yellow()
            ),
        }

        run_bundle_install(&module_path)?;

        verify_required_gems(&module_path)?;

        println!(
            "{} Regent is ready. You can now run `regent test`.",
            "✓".green().bold()
        );
        Ok(())
    }
}

fn ensure_gemfile(module_path: &Path, force: bool) -> anyhow::Result<()> {
    let gemfile = module_path.join("Gemfile");
    if gemfile.exists() && !force {
        return Ok(());
    }

    let mut content = String::from("# Generated by `regent bootstrap`\nsource 'https://rubygems.org'\n\n");
    for (name, req) in REQUIRED_GEMS {
        content.push_str(&format!("gem '{name}', '{req}'\n"));
    }
    std::fs::write(&gemfile, content)?;
    println!(
        "{} Wrote {}",
        "✓".green().bold(),
        gemfile.display()
    );
    Ok(())
}

fn run_bundle_install(module_path: &Path) -> anyhow::Result<()> {
    let bundle = which("bundle");
    let Some(bundle) = bundle else {
        return Err(anyhow::anyhow!(
            "`bundle` was not found on PATH. Install Bundler (`gem install bundler`) and re-run `regent bootstrap`."
        ));
    };

    println!("{} Running `bundle install --path vendor/bundle`", "⚙".cyan());
    let status = Command::new(&bundle)
        .arg("install")
        .arg("--path")
        .arg("vendor/bundle")
        .current_dir(module_path)
        .status()?;

    if !status.success() {
        return Err(anyhow::anyhow!(
            "`bundle install` failed (exit code {:?}). See output above.",
            status.code()
        ));
    }
    Ok(())
}

fn verify_required_gems(module_path: &Path) -> anyhow::Result<()> {
    let bundle_root = module_path.join("vendor").join("bundle").join("ruby");
    let mut missing = Vec::new();
    for (name, _) in REQUIRED_GEMS {
        if !gem_present(&bundle_root, name) {
            missing.push(*name);
        }
    }
    if !missing.is_empty() {
        return Err(anyhow::anyhow!(
            "Bootstrap completed but the following gems are still missing: {}",
            missing.join(", ")
        ));
    }
    Ok(())
}

fn gem_present(bundle_root: &Path, gem_name: &str) -> bool {
    let Ok(entries) = std::fs::read_dir(bundle_root) else {
        return false;
    };
    for entry in entries.flatten() {
        let gems_dir = entry.path().join("gems");
        let Ok(gems) = std::fs::read_dir(&gems_dir) else { continue };
        for gem in gems.flatten() {
            if let Some(name) = gem.file_name().to_str() {
                if name.starts_with(&format!("{gem_name}-")) {
                    return true;
                }
            }
        }
    }
    false
}

fn which(cmd: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(cmd);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

/// Hint shown by other commands when a Regent dependency is missing at runtime.
pub fn missing_dependency_hint(what: &str) -> String {
    format!(
        "{what} was not found.\nRun `regent bootstrap` in your module directory to install Regent's required gems."
    )
}
